# Default values for bugle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

params:
  namespace: default
  podname: kubernetes-bootcamp-6bf84cb898-hsg6w
  username: unset
  password: unset
image:
  repository: cminion/bugle
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: cminion.cf
      paths:
        - "/bugle"

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
