# Default values for LogEar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

params:
  namespace: default #Namespace is the target pod in
  podname:  nihilist-eagle-nginx-ingress-controller-5688d488d5-5lstd     #Name of the target pod
  username: unset #Credentials to secure webpage showing the log. If either of these are set to 'unset' then there is no challenge.
  password: unset
image:
  repository: cminion/logear
  tag: latest
  pullPolicy: Always

imagePullSecrets: []


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: cminion.cf
      paths:
        - "/LogEar"

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
